---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-service
  namespace: springfield
spec:
  hosts: 
    - user-service
  http:
    - match:
      - uri:
        prefix: /
      route:
        - destination:
          host: user-service
          port:
            number: 8600