---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: springfield-ophir-nyc
  namespace: istio-ingress
spec:
  secretName: springfield-ophir-nyc-crt
  dnsNames:
    - springfield.ophir.nyc
  issuerRef:
    name: production-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io